app/players/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.fields.html5 import DateField
from wtforms.validators import Optional, Length, Required, URL, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User, ContentManager


class ProfileForm(Form):
    email = StringField('Email', validators=[Required(), Length(1,64), Email()])
    username = StringField('Username', validators=[Required(), Length(1, 64), \
                        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, 'Username must have only lettters, \
                        numbers or underscore')])
    password = PasswordField('Password', validators=[Required(), \
                           EqualTo('password1', message='Password must match.')])
    password1 = PasswordField('Confirm password', validators=[Required()])
    submit = SubmitField('New')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username has already existed.')


class EditForm(Form):
    email = StringField('Email', validators=[Required(), Length(1,64), Email()])
    username = StringField('Username', validators=[Required(), Length(1, 64), \
                        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, 'Username must have only lettters, \
                        numbers or underscore')])
    password = PasswordField('Password', validators=[EqualTo('password1', message='Password must match.')])
    password1 = PasswordField('Confirm password')
    submit = SubmitField('Edit')


class ContentmanagerForm(Form):
    ip_address = StringField('ServerAddress', validators=[Required()])
    username = StringField('LoginName', validators=[Required()])
    password = PasswordField('LoginPassword', validators=[Required(), EqualTo('password1', message='Password must match.')])
    password1 = PasswordField('Confirm password', validators=[Required()])
    submit = SubmitField('New')

    def validate_ip_address(self, field):
        if ContentManager.query.filter_by(ip_address=field.data).first():
            raise ValidationError('Content manager has already existed.')


class CMEditForm(Form):
    ip_address = StringField('Email', validators=[Required()])
    username = StringField('Username', validators=[Required()])
    password = PasswordField('Password', validators=[EqualTo('password1', message='Password must match.')])
    password1 = PasswordField('Confirm password')
    submit = SubmitField('Edit')

app/players/__init__.py
from flask import Blueprint

players = Blueprint('players', __name__)

from . import routes

app/players/routes.py
from flask import render_template, flash, redirect, url_for, abort, request, current_app
from flask.ext.login import login_required, current_user
from .. import db
from ..models import User, Player, ContentManager
from . import players
from .forms import ProfileForm, EditForm, ContentmanagerForm, CMEditForm
import requests


@players.route('/')
def index():
    try:
        page = request.args.get('page', 1, type=int)
        pagination = Player.query.order_by(Player.last_player_heartbeat.desc()).paginate(
            page, per_page=current_app.config['PLAYER_PER_PAGE'],
            error_out=False)
        players = pagination.items
        cms = ContentManager.query.all()
        return render_template('players/index.html', players=players, cms=cms, pagination=pagination)
    except Exception, e:
        return str(e)



@players.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    users = User.query.all()
    return render_template('players/user.html', user=user, users=users)


@players.route('/players/contentmanager/<int:id>')
def sorted_players(id):
    try:
        cms = ContentManager.query.all()
        cm = ContentManager.query.get_or_404(id)
        page = request.args.get('page', 1, type=int)
        pagination = cm.players.order_by(Player.last_player_heartbeat.desc()).paginate(
            page, per_page=current_app.config['PLAYER_PER_PAGE'],
            error_out=False)
        players = pagination.items
        return render_template('players/sorted_players.html', players=players, cms=cms, pagination=pagination, id=id)
    except Exception, e:
        return str(e)


@players.route('/screen/<int:id>')
def screen(id):
    player = Player.query.get_or_404(id)
    cms = ContentManager.query.all()
    return render_template('players/screen.html', player=player, cms=cms)


@players.route('/user/new', methods=['GET', 'POST'])
@login_required
def new_user():
    form = ProfileForm()
    if form.validate_on_submit():
        email = form.email.data
        username = form.username.data
        password = form.password.data
        user = User(email=email, username=username, password=password)
        db.session.add(user)
        db.session.commit()
        flash('Successfully add a new user.')
        return redirect(url_for('players.user', username=current_user.username))
    return render_template('players/add_user.html', form=form)


@players.route('/user/edit/<username>', methods=['GET', 'POST'])
@login_required
def edit_user(username):
    form = EditForm()
    user = User.query.filter_by(username=username).first_or_404()
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        flash('Successfully edit user.')
        return redirect(url_for('players.user', username=current_user.username))
    form.email.data = user.email
    form.username.data = user.username
    return render_template('players/edit_user.html', form=form)


@players.route('/user/delete/<username>', methods=['GET','POST'])
@login_required
def delete_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    db.session.delete(user)
    db.session.commit()
    flash('Successfully delete a user.')
    return redirect(url_for('players.user', username=current_user.username))


@players.route('/contentmanager')
@login_required
def contentmanager():
    cms = ContentManager.query.all()
    return render_template('players/cm.html', cms=cms)


@players.route('/contentmanager/new', methods=['GET', 'POST'])
@login_required
def new_cm():
    form = ContentmanagerForm()
    if form.validate_on_submit():
        ip_address = form.ip_address.data
        username = form.username.data
        password = form.password.data
        CM_LOGIN = {"username": username, "password": password}
        try:
            r = requests.post("%s/api/rest/auth/login" % ip_address, json=CM_LOGIN)
            authinfo = r.json()
            if authinfo.get('token') is not None:
                cm = ContentManager(ip_address=ip_address, username=username, password=password)
                db.session.add(cm)
                db.session.commit()
                flash('Successfully add a new content manager.')
                return redirect(url_for('players.contentmanager'))
            else:
                flash('Invalid username or password.')
        except Exception, e:
            flash(e)

    return render_template('players/add_cm.html', form=form)

    

@players.route('/contentmanager/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_cm(id):
    form = CMEditForm()
    cm = ContentManager.query.get_or_404(id)
    if form.validate_on_submit():
        cm.ip_address = form.ip_address.data
        cm.username = form.username.data
        cm.password = form.password.data
        db.session.add(cm)
        db.session.commit()
        flash('Successfully edit content manager.')
        return redirect(url_for('players.contentmanager'))
    form.ip_address.data = cm.ip_address
    form.username.data = cm.username
    return render_template('players/edit_user.html', form=form)


@players.route('/contentmanager/delete/<int:id>', methods=['GET','POST'])
@login_required
def delete_cm(id):
    cm = ContentManager.query.get_or_404(id)
    db.session.delete(cm)
    db.session.commit()
    flash('Successfully delete a content manager.')
    return redirect(url_for('players.contentmanager'))

app/templates/players/_cm.html
<tr>
	<td>{{cm.ip_address}}</td>
	<td>
	{% if current_user.is_admin %}
	<a class="btn btn-default btn-xs pull-right" href="{{url_for('players.delete_cm', id=cm.id)}}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
	<a class="btn btn-default btn-xs pull-right" href="{{url_for('players.edit_cm', id=cm.id)}}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
	{% endif %}
	</td>
</tr>

app/templates/players/_player_header.html
<tr>
    <td>{{ player.name }}</td>
    <td><span>{{player.last_player_heartbeat }}</span></td>
    <td><a href="#" data-toggle="modal" data-target="#myModal"><span {% if player.last_player_state=='HEARTBEAT_OVERDUE'%} class="label label-warning" {% else %} class="label label-danger" {% endif %}>{{player.last_player_state }}</span></a></td>
    <td><a href="{{url_for('players.screen', id=player.id)}}">{{ player.last_screen_issue }}</a></td>
</tr>

app/templates/players/_player_modal.html
<!-- Modal -->
<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Detailed Message</h4>
      </div>
      <div class="modal-body">
        {{player.last_player_issue}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/templates/players/_players.html
<table class="table table-hover">
    <thead>
      <tr>
        <th>Player Name</th>
        <th>Last Heartbeat</th>
        <th>Last Player Error</th>
        <th>Last Screen Error</th>
      </tr>
    </thead>
    <tbody>
{% for player in players %}
    {% include "players/_player_header.html" %}
    {% include "players/_player_modal.html" %}
{% endfor %}
    </tbody>
</table>

app/templates/players/_user.html
<tr>
	<td>{{user.username}}</td>
	<td>{{user.email}}</td>
	<td>
	{% if current_user.is_admin %}
	<a class="btn btn-default btn-xs pull-right" href="{{url_for('players.delete_user', username=user.username)}}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
	{% endif%}
	{% if current_user==user or current_user.is_admin %}
	<a class="btn btn-default btn-xs pull-right" href="{{url_for('players.edit_user', username=user.username)}}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
	{% endif %}
	</td>
</tr>

app/templates/players/add_cm.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="page-header">
    <h1>New CM</h1>
</div>

{{wtf.quick_form(form)}}
{% endblock %}

app/templates/players/add_user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>New User</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/players/cm.html
{% extends "base.html" %}

{% block page_content %}
<div class="talk">
    {% if current_user.is_admin %}
    <a class="btn btn-default" href="{{url_for('players.new_cm')}}">New CM</a>
    {% endif %}
          <table class="table table-striped">
            <thead id="tblHead">
              <tr>
                <th>CM Address</th>
              </tr>
            </thead>
            <tbody>
            {% for cm in cms %}
            {% include "players/_cm.html" %}
            {% endfor %}
            </tbody>
          </table>
    
</div>
{% endblock %}

app/templates/players/edit_user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Edit User</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/players/index.html
{% extends "base.html" %}

{% block page_content %}
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        CM
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        {% for cm in cms %}
        <li><a href="{{url_for('players.sorted_players', id=cm.id)}}">{{cm.ip_address}}</a></li>
        {% endfor %}
      </ul>
    </div>
{% include "players/_players.html" %}
{% endblock %}

app/templates/players/screen.html
{% extends "base.html" %}

{% block page_content %}
<div class="talk">
          <table class="table table-striped" id="tblGrid">
            <thead id="tblHead">
              <tr>
                <th>Screen Type</th>
                <th>Power Status</th>
                <th>Resolution</th>
                <th>Brightness</th>
                <th>Contrast</th>
                <th>Powered On Hours</th>
                <th>Backlight On Hours</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{player.screen_type}}</td>
                <td>{{player.power_status}}</td>
                <td>{{player.resolution}}</td>
                <td>{{player.brightness}}</td>
                <td>{{player.contrast}}</td>
                <td>{{player.powered_on_hours}}</td>
                <td>{{player.backlight_on_hours}}</td>
              </tr>
            </tbody>
          </table>
</div>
{% endblock %}

app/templates/players/sorted_players.html
{% extends "base.html" %}
{% import "_macros.html" as macros%}

{% block page_content %}
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        CM
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
        {% for cm in cms %}
        <li><a href="{{url_for('players.sorted_players', id=cm.id)}}">{{cm.ip_address}}</a></li>
        {% endfor %}
      </ul>
    </div>
{% include "players/_players.html" %}
<div class="pagination">
  {{macros.pagination_widget(pagination, '.sorted_players', id=id)}}
</div>
{% endblock %}

{% block scripts %}
{{super()}}
<script type="text/javascript">
  setTimeout(function(){
     window.location.reload(1);
  }, 60000);
</script>
{% endblock %}

app/templates/players/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="talk">
    {% if current_user.is_admin %}
    <a class="btn btn-default" href="{{url_for('players.new_user')}}">New User</a>
    {% endif %}   
          <table class="table table-striped">
            <thead id="tblHead">
              <tr>
                <th>UserName</th>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>
            {% if current_user.is_admin %}
            {% for user in users %}
            {% include "players/_user.html" %}
            {% endfor %}
            {% else %}
            {% include "players/_user.html" %}
            {% endif %}
            </tbody>
          </table>
</div>
{% endblock %}